//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuflageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuflageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Position_des_Transports" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Beschreibung" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Abstand" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Meter" minOccurs="0"/&gt;
 *         &lt;element name="Geschwindigkeit" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Stundenkilometer" minOccurs="0"/&gt;
 *         &lt;element name="Privates_Begleitfahrzeug" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Polizei" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Begleitfahrzeug_mit_WVZA" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Zu_setzendes_STVO_Zeichen" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Schweregrad" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuflageType", propOrder = {
    "positionDesTransports",
    "beschreibung",
    "abstand",
    "geschwindigkeit",
    "privatesBegleitfahrzeug",
    "polizei",
    "begleitfahrzeugMitWVZA",
    "zuSetzendesSTVOZeichen",
    "schweregrad"
})
public class AuflageType {

    @XmlElement(name = "Position_des_Transports")
    protected String positionDesTransports;
    @XmlElement(name = "Beschreibung")
    protected String beschreibung;
    @XmlElement(name = "Abstand")
    protected Meter abstand;
    @XmlElement(name = "Geschwindigkeit")
    protected Stundenkilometer geschwindigkeit;
    @XmlElement(name = "Privates_Begleitfahrzeug")
    protected Boolean privatesBegleitfahrzeug;
    @XmlElement(name = "Polizei")
    protected Boolean polizei;
    @XmlElement(name = "Begleitfahrzeug_mit_WVZA")
    protected Boolean begleitfahrzeugMitWVZA;
    @XmlElement(name = "Zu_setzendes_STVO_Zeichen")
    protected List<String> zuSetzendesSTVOZeichen;
    @XmlElement(name = "Schweregrad", required = true)
    protected BigInteger schweregrad;

    /**
     * Gets the value of the positionDesTransports property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionDesTransports() {
        return positionDesTransports;
    }

    /**
     * Sets the value of the positionDesTransports property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionDesTransports(String value) {
        this.positionDesTransports = value;
    }

    /**
     * Gets the value of the beschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeschreibung() {
        return beschreibung;
    }

    /**
     * Sets the value of the beschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeschreibung(String value) {
        this.beschreibung = value;
    }

    /**
     * Gets the value of the abstand property.
     * 
     * @return
     *     possible object is
     *     {@link Meter }
     *     
     */
    public Meter getAbstand() {
        return abstand;
    }

    /**
     * Sets the value of the abstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meter }
     *     
     */
    public void setAbstand(Meter value) {
        this.abstand = value;
    }

    /**
     * Gets the value of the geschwindigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link Stundenkilometer }
     *     
     */
    public Stundenkilometer getGeschwindigkeit() {
        return geschwindigkeit;
    }

    /**
     * Sets the value of the geschwindigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stundenkilometer }
     *     
     */
    public void setGeschwindigkeit(Stundenkilometer value) {
        this.geschwindigkeit = value;
    }

    /**
     * Gets the value of the privatesBegleitfahrzeug property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrivatesBegleitfahrzeug() {
        return privatesBegleitfahrzeug;
    }

    /**
     * Sets the value of the privatesBegleitfahrzeug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrivatesBegleitfahrzeug(Boolean value) {
        this.privatesBegleitfahrzeug = value;
    }

    /**
     * Gets the value of the polizei property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPolizei() {
        return polizei;
    }

    /**
     * Sets the value of the polizei property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPolizei(Boolean value) {
        this.polizei = value;
    }

    /**
     * Gets the value of the begleitfahrzeugMitWVZA property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBegleitfahrzeugMitWVZA() {
        return begleitfahrzeugMitWVZA;
    }

    /**
     * Sets the value of the begleitfahrzeugMitWVZA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBegleitfahrzeugMitWVZA(Boolean value) {
        this.begleitfahrzeugMitWVZA = value;
    }

    /**
     * Gets the value of the zuSetzendesSTVOZeichen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuSetzendesSTVOZeichen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuSetzendesSTVOZeichen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getZuSetzendesSTVOZeichen() {
        if (zuSetzendesSTVOZeichen == null) {
            zuSetzendesSTVOZeichen = new ArrayList<String>();
        }
        return this.zuSetzendesSTVOZeichen;
    }

    /**
     * Gets the value of the schweregrad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSchweregrad() {
        return schweregrad;
    }

    /**
     * Sets the value of the schweregrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSchweregrad(BigInteger value) {
        this.schweregrad = value;
    }

}
