//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Aufweitung_Verbreit_VerbindType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Aufweitung_Verbreit_VerbindType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Art_der_Verziehung" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType"/&gt;
 *         &lt;element name="Tangentenlaenge" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Meter" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Aufweitung_Verbreit_VerbindType", propOrder = {
    "artDerVerziehung",
    "tangentenlaenge"
})
public class AufweitungVerbreitVerbindType {

    @XmlElement(name = "Art_der_Verziehung", required = true)
    protected KeyValuePropertyType artDerVerziehung;
    @XmlElement(name = "Tangentenlaenge")
    protected Meter tangentenlaenge;

    /**
     * Gets the value of the artDerVerziehung property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getArtDerVerziehung() {
        return artDerVerziehung;
    }

    /**
     * Sets the value of the artDerVerziehung property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setArtDerVerziehung(KeyValuePropertyType value) {
        this.artDerVerziehung = value;
    }

    /**
     * Gets the value of the tangentenlaenge property.
     * 
     * @return
     *     possible object is
     *     {@link Meter }
     *     
     */
    public Meter getTangentenlaenge() {
        return tangentenlaenge;
    }

    /**
     * Sets the value of the tangentenlaenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meter }
     *     
     */
    public void setTangentenlaenge(Meter value) {
        this.tangentenlaenge = value;
    }

}
