//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BogengeometrieType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BogengeometrieType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Bogenpunkt" type="{http://www.okstra.de/okstra/2.018.2}Punkt_ASB-INGPropertyType" maxOccurs="unbounded" minOccurs="3"/&gt;
 *         &lt;element name="Bogenlaenge" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Meter" minOccurs="0"/&gt;
 *         &lt;element name="Stich" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Meter" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BogengeometrieType", propOrder = {
    "bogenpunkt",
    "bogenlaenge",
    "stich"
})
public class BogengeometrieType {

    @XmlElement(name = "Bogenpunkt", required = true)
    protected List<PunktASBINGPropertyType> bogenpunkt;
    @XmlElement(name = "Bogenlaenge")
    protected Meter bogenlaenge;
    @XmlElement(name = "Stich")
    protected Meter stich;

    /**
     * Gets the value of the bogenpunkt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bogenpunkt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBogenpunkt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PunktASBINGPropertyType }
     * 
     * 
     */
    public List<PunktASBINGPropertyType> getBogenpunkt() {
        if (bogenpunkt == null) {
            bogenpunkt = new ArrayList<PunktASBINGPropertyType>();
        }
        return this.bogenpunkt;
    }

    /**
     * Gets the value of the bogenlaenge property.
     * 
     * @return
     *     possible object is
     *     {@link Meter }
     *     
     */
    public Meter getBogenlaenge() {
        return bogenlaenge;
    }

    /**
     * Sets the value of the bogenlaenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meter }
     *     
     */
    public void setBogenlaenge(Meter value) {
        this.bogenlaenge = value;
    }

    /**
     * Gets the value of the stich property.
     * 
     * @return
     *     possible object is
     *     {@link Meter }
     *     
     */
    public Meter getStich() {
        return stich;
    }

    /**
     * Sets the value of the stich property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meter }
     *     
     */
    public void setStich(Meter value) {
        this.stich = value;
    }

}
