//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Daten_zur_GesamtabnahmeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Daten_zur_GesamtabnahmeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Datum_Fertigstellung_real" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Einhaltung_Zwischentermine" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Datum_Schlussrechnung_VOB_soll" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Anzahl_Nachunternehmer_Bauende" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Anzahl" minOccurs="0"/&gt;
 *         &lt;element name="Nachunternehmer_bis_Bauende" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Daten_zur_GesamtabnahmeType", propOrder = {
    "datumFertigstellungReal",
    "einhaltungZwischentermine",
    "datumSchlussrechnungVOBSoll",
    "anzahlNachunternehmerBauende",
    "nachunternehmerBisBauende"
})
public class DatenZurGesamtabnahmeType {

    @XmlElement(name = "Datum_Fertigstellung_real", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumFertigstellungReal;
    @XmlElement(name = "Einhaltung_Zwischentermine")
    protected boolean einhaltungZwischentermine;
    @XmlElement(name = "Datum_Schlussrechnung_VOB_soll", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumSchlussrechnungVOBSoll;
    @XmlElement(name = "Anzahl_Nachunternehmer_Bauende")
    protected BigInteger anzahlNachunternehmerBauende;
    @XmlElement(name = "Nachunternehmer_bis_Bauende")
    protected List<ObjectRefType> nachunternehmerBisBauende;

    /**
     * Gets the value of the datumFertigstellungReal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumFertigstellungReal() {
        return datumFertigstellungReal;
    }

    /**
     * Sets the value of the datumFertigstellungReal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumFertigstellungReal(XMLGregorianCalendar value) {
        this.datumFertigstellungReal = value;
    }

    /**
     * Gets the value of the einhaltungZwischentermine property.
     * 
     */
    public boolean isEinhaltungZwischentermine() {
        return einhaltungZwischentermine;
    }

    /**
     * Sets the value of the einhaltungZwischentermine property.
     * 
     */
    public void setEinhaltungZwischentermine(boolean value) {
        this.einhaltungZwischentermine = value;
    }

    /**
     * Gets the value of the datumSchlussrechnungVOBSoll property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumSchlussrechnungVOBSoll() {
        return datumSchlussrechnungVOBSoll;
    }

    /**
     * Sets the value of the datumSchlussrechnungVOBSoll property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumSchlussrechnungVOBSoll(XMLGregorianCalendar value) {
        this.datumSchlussrechnungVOBSoll = value;
    }

    /**
     * Gets the value of the anzahlNachunternehmerBauende property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlNachunternehmerBauende() {
        return anzahlNachunternehmerBauende;
    }

    /**
     * Sets the value of the anzahlNachunternehmerBauende property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlNachunternehmerBauende(BigInteger value) {
        this.anzahlNachunternehmerBauende = value;
    }

    /**
     * Gets the value of the nachunternehmerBisBauende property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nachunternehmerBisBauende property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNachunternehmerBisBauende().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getNachunternehmerBisBauende() {
        if (nachunternehmerBisBauende == null) {
            nachunternehmerBisBauende = new ArrayList<ObjectRefType>();
        }
        return this.nachunternehmerBisBauende;
    }

}
