//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NachtragType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NachtragType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OKSTRA_ID" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}GUID" minOccurs="0"/&gt;
 *         &lt;element name="zu_Beschriftung" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="referenziert_Fremddatenbestand" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="referenziert_Fremdobjekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="zu_Kommunikationsobjekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Lfd_Nummer_Nachtrag" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="Lfd_Nummer_Nachtrag_Zusatz" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Datum_Abschluss_Nachtrag" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Mehr_Minder_Kosten_real" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}EURO"/&gt;
 *         &lt;element name="Auftragsvolumen_nach_Nachtrag" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}EURO"/&gt;
 *         &lt;element name="Neues_Datum_Bauende" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Neue_Bauzeit_Wochentage" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Tage" minOccurs="0"/&gt;
 *         &lt;element name="zu_Baumassnahme" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NachtragType", propOrder = {
    "okstraid",
    "zuBeschriftung",
    "referenziertFremddatenbestand",
    "referenziertFremdobjekt",
    "zuKommunikationsobjekt",
    "lfdNummerNachtrag",
    "lfdNummerNachtragZusatz",
    "datumAbschlussNachtrag",
    "mehrMinderKostenReal",
    "auftragsvolumenNachNachtrag",
    "neuesDatumBauende",
    "neueBauzeitWochentage",
    "zuBaumassnahme"
})
public class NachtragType
    extends AbstractFeatureType
{

    @XmlElement(name = "OKSTRA_ID")
    protected String okstraid;
    @XmlElement(name = "zu_Beschriftung")
    protected List<ObjectRefType> zuBeschriftung;
    @XmlElement(name = "referenziert_Fremddatenbestand")
    protected List<ObjectRefType> referenziertFremddatenbestand;
    @XmlElement(name = "referenziert_Fremdobjekt")
    protected List<ObjectRefType> referenziertFremdobjekt;
    @XmlElement(name = "zu_Kommunikationsobjekt")
    protected List<ObjectRefType> zuKommunikationsobjekt;
    @XmlElement(name = "Lfd_Nummer_Nachtrag", required = true)
    protected BigInteger lfdNummerNachtrag;
    @XmlElement(name = "Lfd_Nummer_Nachtrag_Zusatz")
    protected String lfdNummerNachtragZusatz;
    @XmlElement(name = "Datum_Abschluss_Nachtrag", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumAbschlussNachtrag;
    @XmlElement(name = "Mehr_Minder_Kosten_real", required = true)
    protected EURO mehrMinderKostenReal;
    @XmlElement(name = "Auftragsvolumen_nach_Nachtrag", required = true)
    protected EURO auftragsvolumenNachNachtrag;
    @XmlElement(name = "Neues_Datum_Bauende")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar neuesDatumBauende;
    @XmlElement(name = "Neue_Bauzeit_Wochentage")
    protected Tage neueBauzeitWochentage;
    @XmlElement(name = "zu_Baumassnahme")
    protected List<ObjectRefType> zuBaumassnahme;

    /**
     * Gets the value of the okstraid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKSTRAID() {
        return okstraid;
    }

    /**
     * Sets the value of the okstraid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKSTRAID(String value) {
        this.okstraid = value;
    }

    /**
     * Gets the value of the zuBeschriftung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuBeschriftung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuBeschriftung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getZuBeschriftung() {
        if (zuBeschriftung == null) {
            zuBeschriftung = new ArrayList<ObjectRefType>();
        }
        return this.zuBeschriftung;
    }

    /**
     * Gets the value of the referenziertFremddatenbestand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenziertFremddatenbestand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenziertFremddatenbestand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getReferenziertFremddatenbestand() {
        if (referenziertFremddatenbestand == null) {
            referenziertFremddatenbestand = new ArrayList<ObjectRefType>();
        }
        return this.referenziertFremddatenbestand;
    }

    /**
     * Gets the value of the referenziertFremdobjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenziertFremdobjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenziertFremdobjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getReferenziertFremdobjekt() {
        if (referenziertFremdobjekt == null) {
            referenziertFremdobjekt = new ArrayList<ObjectRefType>();
        }
        return this.referenziertFremdobjekt;
    }

    /**
     * Gets the value of the zuKommunikationsobjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuKommunikationsobjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuKommunikationsobjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getZuKommunikationsobjekt() {
        if (zuKommunikationsobjekt == null) {
            zuKommunikationsobjekt = new ArrayList<ObjectRefType>();
        }
        return this.zuKommunikationsobjekt;
    }

    /**
     * Gets the value of the lfdNummerNachtrag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLfdNummerNachtrag() {
        return lfdNummerNachtrag;
    }

    /**
     * Sets the value of the lfdNummerNachtrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLfdNummerNachtrag(BigInteger value) {
        this.lfdNummerNachtrag = value;
    }

    /**
     * Gets the value of the lfdNummerNachtragZusatz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLfdNummerNachtragZusatz() {
        return lfdNummerNachtragZusatz;
    }

    /**
     * Sets the value of the lfdNummerNachtragZusatz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLfdNummerNachtragZusatz(String value) {
        this.lfdNummerNachtragZusatz = value;
    }

    /**
     * Gets the value of the datumAbschlussNachtrag property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumAbschlussNachtrag() {
        return datumAbschlussNachtrag;
    }

    /**
     * Sets the value of the datumAbschlussNachtrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumAbschlussNachtrag(XMLGregorianCalendar value) {
        this.datumAbschlussNachtrag = value;
    }

    /**
     * Gets the value of the mehrMinderKostenReal property.
     * 
     * @return
     *     possible object is
     *     {@link EURO }
     *     
     */
    public EURO getMehrMinderKostenReal() {
        return mehrMinderKostenReal;
    }

    /**
     * Sets the value of the mehrMinderKostenReal property.
     * 
     * @param value
     *     allowed object is
     *     {@link EURO }
     *     
     */
    public void setMehrMinderKostenReal(EURO value) {
        this.mehrMinderKostenReal = value;
    }

    /**
     * Gets the value of the auftragsvolumenNachNachtrag property.
     * 
     * @return
     *     possible object is
     *     {@link EURO }
     *     
     */
    public EURO getAuftragsvolumenNachNachtrag() {
        return auftragsvolumenNachNachtrag;
    }

    /**
     * Sets the value of the auftragsvolumenNachNachtrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link EURO }
     *     
     */
    public void setAuftragsvolumenNachNachtrag(EURO value) {
        this.auftragsvolumenNachNachtrag = value;
    }

    /**
     * Gets the value of the neuesDatumBauende property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNeuesDatumBauende() {
        return neuesDatumBauende;
    }

    /**
     * Sets the value of the neuesDatumBauende property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNeuesDatumBauende(XMLGregorianCalendar value) {
        this.neuesDatumBauende = value;
    }

    /**
     * Gets the value of the neueBauzeitWochentage property.
     * 
     * @return
     *     possible object is
     *     {@link Tage }
     *     
     */
    public Tage getNeueBauzeitWochentage() {
        return neueBauzeitWochentage;
    }

    /**
     * Sets the value of the neueBauzeitWochentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tage }
     *     
     */
    public void setNeueBauzeitWochentage(Tage value) {
        this.neueBauzeitWochentage = value;
    }

    /**
     * Gets the value of the zuBaumassnahme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuBaumassnahme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuBaumassnahme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getZuBaumassnahme() {
        if (zuBaumassnahme == null) {
            zuBaumassnahme = new ArrayList<ObjectRefType>();
        }
        return this.zuBaumassnahme;
    }

}
