//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpenLR_LineAttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpenLR_LineAttributesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FRC" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType"/&gt;
 *         &lt;element name="FOW" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType"/&gt;
 *         &lt;element name="BEAR" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Grad"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpenLR_LineAttributesType", propOrder = {
    "frc",
    "fow",
    "bear"
})
public class OpenLRLineAttributesType {

    @XmlElement(name = "FRC", required = true)
    protected KeyValuePropertyType frc;
    @XmlElement(name = "FOW", required = true)
    protected KeyValuePropertyType fow;
    @XmlElement(name = "BEAR", required = true)
    protected Grad bear;

    /**
     * Gets the value of the frc property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getFRC() {
        return frc;
    }

    /**
     * Sets the value of the frc property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setFRC(KeyValuePropertyType value) {
        this.frc = value;
    }

    /**
     * Gets the value of the fow property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getFOW() {
        return fow;
    }

    /**
     * Sets the value of the fow property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setFOW(KeyValuePropertyType value) {
        this.fow = value;
    }

    /**
     * Gets the value of the bear property.
     * 
     * @return
     *     possible object is
     *     {@link Grad }
     *     
     */
    public Grad getBEAR() {
        return bear;
    }

    /**
     * Sets the value of the bear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grad }
     *     
     */
    public void setBEAR(Grad value) {
        this.bear = value;
    }

}
