//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QN_PunktType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QN_PunktType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Station" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Meter"/&gt;
 *         &lt;element name="Querneigung" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Prozent_Neigung" minOccurs="0"/&gt;
 *         &lt;element name="automatische_Berechnung" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Verziehungsform" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QN_PunktType", propOrder = {
    "station",
    "querneigung",
    "automatischeBerechnung",
    "verziehungsform"
})
public class QNPunktType {

    @XmlElement(name = "Station", required = true)
    protected Meter station;
    @XmlElement(name = "Querneigung")
    protected ProzentNeigung querneigung;
    @XmlElement(name = "automatische_Berechnung")
    protected Boolean automatischeBerechnung;
    @XmlElement(name = "Verziehungsform")
    protected KeyValuePropertyType verziehungsform;

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link Meter }
     *     
     */
    public Meter getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meter }
     *     
     */
    public void setStation(Meter value) {
        this.station = value;
    }

    /**
     * Gets the value of the querneigung property.
     * 
     * @return
     *     possible object is
     *     {@link ProzentNeigung }
     *     
     */
    public ProzentNeigung getQuerneigung() {
        return querneigung;
    }

    /**
     * Sets the value of the querneigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProzentNeigung }
     *     
     */
    public void setQuerneigung(ProzentNeigung value) {
        this.querneigung = value;
    }

    /**
     * Gets the value of the automatischeBerechnung property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutomatischeBerechnung() {
        return automatischeBerechnung;
    }

    /**
     * Sets the value of the automatischeBerechnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutomatischeBerechnung(Boolean value) {
        this.automatischeBerechnung = value;
    }

    /**
     * Gets the value of the verziehungsform property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getVerziehungsform() {
        return verziehungsform;
    }

    /**
     * Sets the value of the verziehungsform property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setVerziehungsform(KeyValuePropertyType value) {
        this.verziehungsform = value;
    }

}
