//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TabellenspalteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TabellenspalteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Spaltennummer" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="Bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Spaltenart" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType"/&gt;
 *         &lt;element name="Beschreibung" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Berechnung_Spaltensumme" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Rechenvorschrift" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Masseinheit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Tabellenfeld" type="{http://www.okstra.de/okstra/2.018.2}TabellenfeldPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TabellenspalteType", propOrder = {
    "spaltennummer",
    "bezeichnung",
    "spaltenart",
    "beschreibung",
    "berechnungSpaltensumme",
    "rechenvorschrift",
    "masseinheit",
    "tabellenfeld"
})
public class TabellenspalteType {

    @XmlElement(name = "Spaltennummer", required = true)
    protected BigInteger spaltennummer;
    @XmlElement(name = "Bezeichnung", required = true)
    protected String bezeichnung;
    @XmlElement(name = "Spaltenart", required = true)
    protected KeyValuePropertyType spaltenart;
    @XmlElement(name = "Beschreibung")
    protected String beschreibung;
    @XmlElement(name = "Berechnung_Spaltensumme")
    protected Boolean berechnungSpaltensumme;
    @XmlElement(name = "Rechenvorschrift")
    protected String rechenvorschrift;
    @XmlElement(name = "Masseinheit")
    protected String masseinheit;
    @XmlElement(name = "Tabellenfeld")
    protected List<TabellenfeldPropertyType> tabellenfeld;

    /**
     * Gets the value of the spaltennummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpaltennummer() {
        return spaltennummer;
    }

    /**
     * Sets the value of the spaltennummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpaltennummer(BigInteger value) {
        this.spaltennummer = value;
    }

    /**
     * Gets the value of the bezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnung() {
        return bezeichnung;
    }

    /**
     * Sets the value of the bezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnung(String value) {
        this.bezeichnung = value;
    }

    /**
     * Gets the value of the spaltenart property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getSpaltenart() {
        return spaltenart;
    }

    /**
     * Sets the value of the spaltenart property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setSpaltenart(KeyValuePropertyType value) {
        this.spaltenart = value;
    }

    /**
     * Gets the value of the beschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeschreibung() {
        return beschreibung;
    }

    /**
     * Sets the value of the beschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeschreibung(String value) {
        this.beschreibung = value;
    }

    /**
     * Gets the value of the berechnungSpaltensumme property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBerechnungSpaltensumme() {
        return berechnungSpaltensumme;
    }

    /**
     * Sets the value of the berechnungSpaltensumme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBerechnungSpaltensumme(Boolean value) {
        this.berechnungSpaltensumme = value;
    }

    /**
     * Gets the value of the rechenvorschrift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRechenvorschrift() {
        return rechenvorschrift;
    }

    /**
     * Sets the value of the rechenvorschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRechenvorschrift(String value) {
        this.rechenvorschrift = value;
    }

    /**
     * Gets the value of the masseinheit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasseinheit() {
        return masseinheit;
    }

    /**
     * Sets the value of the masseinheit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasseinheit(String value) {
        this.masseinheit = value;
    }

    /**
     * Gets the value of the tabellenfeld property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tabellenfeld property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTabellenfeld().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TabellenfeldPropertyType }
     * 
     * 
     */
    public List<TabellenfeldPropertyType> getTabellenfeld() {
        if (tabellenfeld == null) {
            tabellenfeld = new ArrayList<TabellenfeldPropertyType>();
        }
        return this.tabellenfeld;
    }

}
