//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TieftemperaturverhaltenType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TieftemperaturverhaltenType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Prueftemperatur" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType"/&gt;
 *         &lt;element name="Biegekriechsteifigkeit" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="mWert" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Temperatur_m03" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Grad_Celsius"/&gt;
 *         &lt;element name="Temperatur_S300" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}Grad_Celsius"/&gt;
 *         &lt;element name="Pruefgeraet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Alterungszustand_Bindemittel" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TieftemperaturverhaltenType", propOrder = {
    "prueftemperatur",
    "biegekriechsteifigkeit",
    "mWert",
    "temperaturM03",
    "temperaturS300",
    "pruefgeraet",
    "alterungszustandBindemittel"
})
public class TieftemperaturverhaltenType {

    @XmlElement(name = "Prueftemperatur", required = true)
    protected KeyValuePropertyType prueftemperatur;
    @XmlElement(name = "Biegekriechsteifigkeit")
    protected BigInteger biegekriechsteifigkeit;
    protected double mWert;
    @XmlElement(name = "Temperatur_m03", required = true)
    protected GradCelsius temperaturM03;
    @XmlElement(name = "Temperatur_S300", required = true)
    protected GradCelsius temperaturS300;
    @XmlElement(name = "Pruefgeraet")
    protected String pruefgeraet;
    @XmlElement(name = "Alterungszustand_Bindemittel")
    protected KeyValuePropertyType alterungszustandBindemittel;

    /**
     * Gets the value of the prueftemperatur property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getPrueftemperatur() {
        return prueftemperatur;
    }

    /**
     * Sets the value of the prueftemperatur property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setPrueftemperatur(KeyValuePropertyType value) {
        this.prueftemperatur = value;
    }

    /**
     * Gets the value of the biegekriechsteifigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBiegekriechsteifigkeit() {
        return biegekriechsteifigkeit;
    }

    /**
     * Sets the value of the biegekriechsteifigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBiegekriechsteifigkeit(BigInteger value) {
        this.biegekriechsteifigkeit = value;
    }

    /**
     * Gets the value of the mWert property.
     * 
     */
    public double getMWert() {
        return mWert;
    }

    /**
     * Sets the value of the mWert property.
     * 
     */
    public void setMWert(double value) {
        this.mWert = value;
    }

    /**
     * Gets the value of the temperaturM03 property.
     * 
     * @return
     *     possible object is
     *     {@link GradCelsius }
     *     
     */
    public GradCelsius getTemperaturM03() {
        return temperaturM03;
    }

    /**
     * Sets the value of the temperaturM03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GradCelsius }
     *     
     */
    public void setTemperaturM03(GradCelsius value) {
        this.temperaturM03 = value;
    }

    /**
     * Gets the value of the temperaturS300 property.
     * 
     * @return
     *     possible object is
     *     {@link GradCelsius }
     *     
     */
    public GradCelsius getTemperaturS300() {
        return temperaturS300;
    }

    /**
     * Sets the value of the temperaturS300 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GradCelsius }
     *     
     */
    public void setTemperaturS300(GradCelsius value) {
        this.temperaturS300 = value;
    }

    /**
     * Gets the value of the pruefgeraet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPruefgeraet() {
        return pruefgeraet;
    }

    /**
     * Sets the value of the pruefgeraet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPruefgeraet(String value) {
        this.pruefgeraet = value;
    }

    /**
     * Gets the value of the alterungszustandBindemittel property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getAlterungszustandBindemittel() {
        return alterungszustandBindemittel;
    }

    /**
     * Sets the value of the alterungszustandBindemittel property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setAlterungszustandBindemittel(KeyValuePropertyType value) {
        this.alterungszustandBindemittel = value;
    }

}
