//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TMC_PunktlokationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TMC_PunktlokationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OKSTRA_ID" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}GUID" minOccurs="0"/&gt;
 *         &lt;element name="zu_Beschriftung" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="referenziert_Fremddatenbestand" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="referenziert_Fremdobjekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="zu_Kommunikationsobjekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="bei_Strassenpunkt" type="{http://www.okstra.de/okstra/2.018.2}StrassenpunktPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="bei_Strassenelementpunkt" type="{http://www.okstra.de/okstra/2.018.2}StrassenelementpunktPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Geometrie_Punktobjekt" type="{http://www.opengis.net/gml/3.2}PointPropertyType" minOccurs="0"/&gt;
 *         &lt;element name="OpenLR_Punktobjekt" type="{http://www.okstra.de/okstra/2.018.2}OpenLR_PointLocationReferencePropertyType" minOccurs="0"/&gt;
 *         &lt;element name="TMC_Punktobjekt" type="{http://www.okstra.de/okstra/2.018.2}TMC_PunktreferenzPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Location_Code" type="{http://www.okstra.de/okstra/2.018.2}TMC_Location_CodePropertyType"/&gt;
 *         &lt;element name="begrenzt_am_Anfang" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="begrenzt_am_Ende" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="identisch_mit" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" minOccurs="0"/&gt;
 *         &lt;element name="identisch_zu" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TMC_PunktlokationType", propOrder = {
    "okstraid",
    "zuBeschriftung",
    "referenziertFremddatenbestand",
    "referenziertFremdobjekt",
    "zuKommunikationsobjekt",
    "beiStrassenpunkt",
    "beiStrassenelementpunkt",
    "geometriePunktobjekt",
    "openLRPunktobjekt",
    "tmcPunktobjekt",
    "locationCode",
    "begrenztAmAnfang",
    "begrenztAmEnde",
    "identischMit",
    "identischZu"
})
public class TMCPunktlokationType
    extends AbstractFeatureType
{

    @XmlElement(name = "OKSTRA_ID")
    protected String okstraid;
    @XmlElement(name = "zu_Beschriftung")
    protected List<ObjectRefType> zuBeschriftung;
    @XmlElement(name = "referenziert_Fremddatenbestand")
    protected List<ObjectRefType> referenziertFremddatenbestand;
    @XmlElement(name = "referenziert_Fremdobjekt")
    protected List<ObjectRefType> referenziertFremdobjekt;
    @XmlElement(name = "zu_Kommunikationsobjekt")
    protected List<ObjectRefType> zuKommunikationsobjekt;
    @XmlElement(name = "bei_Strassenpunkt")
    protected List<StrassenpunktPropertyType> beiStrassenpunkt;
    @XmlElement(name = "bei_Strassenelementpunkt")
    protected List<StrassenelementpunktPropertyType> beiStrassenelementpunkt;
    @XmlElement(name = "Geometrie_Punktobjekt")
    protected PointPropertyType geometriePunktobjekt;
    @XmlElement(name = "OpenLR_Punktobjekt")
    protected OpenLRPointLocationReferencePropertyType openLRPunktobjekt;
    @XmlElement(name = "TMC_Punktobjekt")
    protected List<TMCPunktreferenzPropertyType> tmcPunktobjekt;
    @XmlElement(name = "Location_Code", required = true)
    protected TMCLocationCodePropertyType locationCode;
    @XmlElement(name = "begrenzt_am_Anfang")
    protected List<ObjectRefType> begrenztAmAnfang;
    @XmlElement(name = "begrenzt_am_Ende")
    protected List<ObjectRefType> begrenztAmEnde;
    @XmlElement(name = "identisch_mit")
    protected ObjectRefType identischMit;
    @XmlElement(name = "identisch_zu")
    protected ObjectRefType identischZu;

    /**
     * Gets the value of the okstraid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKSTRAID() {
        return okstraid;
    }

    /**
     * Sets the value of the okstraid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKSTRAID(String value) {
        this.okstraid = value;
    }

    /**
     * Gets the value of the zuBeschriftung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuBeschriftung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuBeschriftung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getZuBeschriftung() {
        if (zuBeschriftung == null) {
            zuBeschriftung = new ArrayList<ObjectRefType>();
        }
        return this.zuBeschriftung;
    }

    /**
     * Gets the value of the referenziertFremddatenbestand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenziertFremddatenbestand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenziertFremddatenbestand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getReferenziertFremddatenbestand() {
        if (referenziertFremddatenbestand == null) {
            referenziertFremddatenbestand = new ArrayList<ObjectRefType>();
        }
        return this.referenziertFremddatenbestand;
    }

    /**
     * Gets the value of the referenziertFremdobjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenziertFremdobjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenziertFremdobjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getReferenziertFremdobjekt() {
        if (referenziertFremdobjekt == null) {
            referenziertFremdobjekt = new ArrayList<ObjectRefType>();
        }
        return this.referenziertFremdobjekt;
    }

    /**
     * Gets the value of the zuKommunikationsobjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuKommunikationsobjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuKommunikationsobjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getZuKommunikationsobjekt() {
        if (zuKommunikationsobjekt == null) {
            zuKommunikationsobjekt = new ArrayList<ObjectRefType>();
        }
        return this.zuKommunikationsobjekt;
    }

    /**
     * Gets the value of the beiStrassenpunkt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beiStrassenpunkt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeiStrassenpunkt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StrassenpunktPropertyType }
     * 
     * 
     */
    public List<StrassenpunktPropertyType> getBeiStrassenpunkt() {
        if (beiStrassenpunkt == null) {
            beiStrassenpunkt = new ArrayList<StrassenpunktPropertyType>();
        }
        return this.beiStrassenpunkt;
    }

    /**
     * Gets the value of the beiStrassenelementpunkt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beiStrassenelementpunkt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeiStrassenelementpunkt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StrassenelementpunktPropertyType }
     * 
     * 
     */
    public List<StrassenelementpunktPropertyType> getBeiStrassenelementpunkt() {
        if (beiStrassenelementpunkt == null) {
            beiStrassenelementpunkt = new ArrayList<StrassenelementpunktPropertyType>();
        }
        return this.beiStrassenelementpunkt;
    }

    /**
     * Gets the value of the geometriePunktobjekt property.
     * 
     * @return
     *     possible object is
     *     {@link PointPropertyType }
     *     
     */
    public PointPropertyType getGeometriePunktobjekt() {
        return geometriePunktobjekt;
    }

    /**
     * Sets the value of the geometriePunktobjekt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointPropertyType }
     *     
     */
    public void setGeometriePunktobjekt(PointPropertyType value) {
        this.geometriePunktobjekt = value;
    }

    /**
     * Gets the value of the openLRPunktobjekt property.
     * 
     * @return
     *     possible object is
     *     {@link OpenLRPointLocationReferencePropertyType }
     *     
     */
    public OpenLRPointLocationReferencePropertyType getOpenLRPunktobjekt() {
        return openLRPunktobjekt;
    }

    /**
     * Sets the value of the openLRPunktobjekt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenLRPointLocationReferencePropertyType }
     *     
     */
    public void setOpenLRPunktobjekt(OpenLRPointLocationReferencePropertyType value) {
        this.openLRPunktobjekt = value;
    }

    /**
     * Gets the value of the tmcPunktobjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmcPunktobjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTMCPunktobjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TMCPunktreferenzPropertyType }
     * 
     * 
     */
    public List<TMCPunktreferenzPropertyType> getTMCPunktobjekt() {
        if (tmcPunktobjekt == null) {
            tmcPunktobjekt = new ArrayList<TMCPunktreferenzPropertyType>();
        }
        return this.tmcPunktobjekt;
    }

    /**
     * Gets the value of the locationCode property.
     * 
     * @return
     *     possible object is
     *     {@link TMCLocationCodePropertyType }
     *     
     */
    public TMCLocationCodePropertyType getLocationCode() {
        return locationCode;
    }

    /**
     * Sets the value of the locationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMCLocationCodePropertyType }
     *     
     */
    public void setLocationCode(TMCLocationCodePropertyType value) {
        this.locationCode = value;
    }

    /**
     * Gets the value of the begrenztAmAnfang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the begrenztAmAnfang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBegrenztAmAnfang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getBegrenztAmAnfang() {
        if (begrenztAmAnfang == null) {
            begrenztAmAnfang = new ArrayList<ObjectRefType>();
        }
        return this.begrenztAmAnfang;
    }

    /**
     * Gets the value of the begrenztAmEnde property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the begrenztAmEnde property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBegrenztAmEnde().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getBegrenztAmEnde() {
        if (begrenztAmEnde == null) {
            begrenztAmEnde = new ArrayList<ObjectRefType>();
        }
        return this.begrenztAmEnde;
    }

    /**
     * Gets the value of the identischMit property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRefType }
     *     
     */
    public ObjectRefType getIdentischMit() {
        return identischMit;
    }

    /**
     * Sets the value of the identischMit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRefType }
     *     
     */
    public void setIdentischMit(ObjectRefType value) {
        this.identischMit = value;
    }

    /**
     * Gets the value of the identischZu property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRefType }
     *     
     */
    public ObjectRefType getIdentischZu() {
        return identischZu;
    }

    /**
     * Sets the value of the identischZu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRefType }
     *     
     */
    public void setIdentischZu(ObjectRefType value) {
        this.identischZu = value;
    }

}
