//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TunnelbeleuchtungsinfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TunnelbeleuchtungsinfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Blendschutz_ueber_Portal" type="{http://www.okstra.de/okstra/2.018.2}Anzahl_unscharfPropertyType" minOccurs="0"/&gt;
 *         &lt;element name="Art_Blendschutz_ueber_Portal" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType" minOccurs="0"/&gt;
 *         &lt;element name="Vorfeldbeleuchtung" type="{http://www.okstra.de/okstra/2.018.2}Anzahl_unscharfPropertyType" minOccurs="0"/&gt;
 *         &lt;element name="Beleuchtungsart_Einfahrtsbeleuchtung" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType" minOccurs="0"/&gt;
 *         &lt;element name="Lampenart_Einfahrtsbeleuchtung" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Durchfahrtsbeleuchtung" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Lampenart_Durchfahrtsbeleuchtung" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Bemerkungen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TunnelbeleuchtungsinfoType", propOrder = {
    "blendschutzUeberPortal",
    "artBlendschutzUeberPortal",
    "vorfeldbeleuchtung",
    "beleuchtungsartEinfahrtsbeleuchtung",
    "lampenartEinfahrtsbeleuchtung",
    "durchfahrtsbeleuchtung",
    "lampenartDurchfahrtsbeleuchtung",
    "bemerkungen"
})
public class TunnelbeleuchtungsinfoType {

    @XmlElement(name = "Blendschutz_ueber_Portal")
    protected AnzahlUnscharfPropertyType blendschutzUeberPortal;
    @XmlElement(name = "Art_Blendschutz_ueber_Portal")
    protected KeyValuePropertyType artBlendschutzUeberPortal;
    @XmlElement(name = "Vorfeldbeleuchtung")
    protected AnzahlUnscharfPropertyType vorfeldbeleuchtung;
    @XmlElement(name = "Beleuchtungsart_Einfahrtsbeleuchtung")
    protected KeyValuePropertyType beleuchtungsartEinfahrtsbeleuchtung;
    @XmlElement(name = "Lampenart_Einfahrtsbeleuchtung")
    protected List<KeyValuePropertyType> lampenartEinfahrtsbeleuchtung;
    @XmlElement(name = "Durchfahrtsbeleuchtung")
    protected Boolean durchfahrtsbeleuchtung;
    @XmlElement(name = "Lampenart_Durchfahrtsbeleuchtung")
    protected List<KeyValuePropertyType> lampenartDurchfahrtsbeleuchtung;
    @XmlElement(name = "Bemerkungen")
    protected String bemerkungen;

    /**
     * Gets the value of the blendschutzUeberPortal property.
     * 
     * @return
     *     possible object is
     *     {@link AnzahlUnscharfPropertyType }
     *     
     */
    public AnzahlUnscharfPropertyType getBlendschutzUeberPortal() {
        return blendschutzUeberPortal;
    }

    /**
     * Sets the value of the blendschutzUeberPortal property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnzahlUnscharfPropertyType }
     *     
     */
    public void setBlendschutzUeberPortal(AnzahlUnscharfPropertyType value) {
        this.blendschutzUeberPortal = value;
    }

    /**
     * Gets the value of the artBlendschutzUeberPortal property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getArtBlendschutzUeberPortal() {
        return artBlendschutzUeberPortal;
    }

    /**
     * Sets the value of the artBlendschutzUeberPortal property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setArtBlendschutzUeberPortal(KeyValuePropertyType value) {
        this.artBlendschutzUeberPortal = value;
    }

    /**
     * Gets the value of the vorfeldbeleuchtung property.
     * 
     * @return
     *     possible object is
     *     {@link AnzahlUnscharfPropertyType }
     *     
     */
    public AnzahlUnscharfPropertyType getVorfeldbeleuchtung() {
        return vorfeldbeleuchtung;
    }

    /**
     * Sets the value of the vorfeldbeleuchtung property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnzahlUnscharfPropertyType }
     *     
     */
    public void setVorfeldbeleuchtung(AnzahlUnscharfPropertyType value) {
        this.vorfeldbeleuchtung = value;
    }

    /**
     * Gets the value of the beleuchtungsartEinfahrtsbeleuchtung property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getBeleuchtungsartEinfahrtsbeleuchtung() {
        return beleuchtungsartEinfahrtsbeleuchtung;
    }

    /**
     * Sets the value of the beleuchtungsartEinfahrtsbeleuchtung property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setBeleuchtungsartEinfahrtsbeleuchtung(KeyValuePropertyType value) {
        this.beleuchtungsartEinfahrtsbeleuchtung = value;
    }

    /**
     * Gets the value of the lampenartEinfahrtsbeleuchtung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lampenartEinfahrtsbeleuchtung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLampenartEinfahrtsbeleuchtung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePropertyType }
     * 
     * 
     */
    public List<KeyValuePropertyType> getLampenartEinfahrtsbeleuchtung() {
        if (lampenartEinfahrtsbeleuchtung == null) {
            lampenartEinfahrtsbeleuchtung = new ArrayList<KeyValuePropertyType>();
        }
        return this.lampenartEinfahrtsbeleuchtung;
    }

    /**
     * Gets the value of the durchfahrtsbeleuchtung property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDurchfahrtsbeleuchtung() {
        return durchfahrtsbeleuchtung;
    }

    /**
     * Sets the value of the durchfahrtsbeleuchtung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDurchfahrtsbeleuchtung(Boolean value) {
        this.durchfahrtsbeleuchtung = value;
    }

    /**
     * Gets the value of the lampenartDurchfahrtsbeleuchtung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lampenartDurchfahrtsbeleuchtung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLampenartDurchfahrtsbeleuchtung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePropertyType }
     * 
     * 
     */
    public List<KeyValuePropertyType> getLampenartDurchfahrtsbeleuchtung() {
        if (lampenartDurchfahrtsbeleuchtung == null) {
            lampenartDurchfahrtsbeleuchtung = new ArrayList<KeyValuePropertyType>();
        }
        return this.lampenartDurchfahrtsbeleuchtung;
    }

    /**
     * Gets the value of the bemerkungen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBemerkungen() {
        return bemerkungen;
    }

    /**
     * Sets the value of the bemerkungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBemerkungen(String value) {
        this.bemerkungen = value;
    }

}
