//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class XlinkTitle
    extends JAXBElement<TitleEltType>
{

    protected final static QName NAME = new QName("http://www.w3.org/1999/xlink", "title");

    public XlinkTitle(TitleEltType value) {
        super(NAME, ((Class) TitleEltType.class), null, value);
    }

    public XlinkTitle() {
        super(NAME, ((Class) TitleEltType.class), null, null);
    }

}
