//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZEB_ProjektType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZEB_ProjektType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OKSTRA_ID" type="{http://www.okstra.de/okstra/2.018.2/okstra-typen}GUID" minOccurs="0"/&gt;
 *         &lt;element name="zu_Beschriftung" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="referenziert_Fremddatenbestand" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="referenziert_Fremdobjekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="zu_Kommunikationsobjekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Kurzbezeichnung_ZEB_Kamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ZEB_Projekt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Hauptmessverfahren" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Zweck" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Umfang" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Zeitabschnitt" type="{http://www.okstra.de/okstra/2.018.2}ZeitabschnittPropertyType" minOccurs="0"/&gt;
 *         &lt;element name="hat_ZEB_Objekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hat_ZEB_Subjekt" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hat_ZEB_Parameterliste" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType"/&gt;
 *         &lt;element name="hat_ZEB_Ereignis" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}ObjectRefType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZEB_ProjektType", propOrder = {
    "okstraid",
    "zuBeschriftung",
    "referenziertFremddatenbestand",
    "referenziertFremdobjekt",
    "zuKommunikationsobjekt",
    "kurzbezeichnungZEBKamp",
    "zebProjekt",
    "hauptmessverfahren",
    "zweck",
    "umfang",
    "zeitabschnitt",
    "hatZEBObjekt",
    "hatZEBSubjekt",
    "hatZEBParameterliste",
    "hatZEBEreignis"
})
public class ZEBProjektType
    extends AbstractFeatureType
{

    @XmlElement(name = "OKSTRA_ID")
    protected String okstraid;
    @XmlElement(name = "zu_Beschriftung")
    protected List<ObjectRefType> zuBeschriftung;
    @XmlElement(name = "referenziert_Fremddatenbestand")
    protected List<ObjectRefType> referenziertFremddatenbestand;
    @XmlElement(name = "referenziert_Fremdobjekt")
    protected List<ObjectRefType> referenziertFremdobjekt;
    @XmlElement(name = "zu_Kommunikationsobjekt")
    protected List<ObjectRefType> zuKommunikationsobjekt;
    @XmlElement(name = "Kurzbezeichnung_ZEB_Kamp")
    protected String kurzbezeichnungZEBKamp;
    @XmlElement(name = "ZEB_Projekt")
    protected String zebProjekt;
    @XmlElement(name = "Hauptmessverfahren")
    protected String hauptmessverfahren;
    @XmlElement(name = "Zweck")
    protected String zweck;
    @XmlElement(name = "Umfang")
    protected String umfang;
    @XmlElement(name = "Zeitabschnitt")
    protected ZeitabschnittPropertyType zeitabschnitt;
    @XmlElement(name = "hat_ZEB_Objekt")
    protected List<ObjectRefType> hatZEBObjekt;
    @XmlElement(name = "hat_ZEB_Subjekt")
    protected List<ObjectRefType> hatZEBSubjekt;
    @XmlElement(name = "hat_ZEB_Parameterliste", required = true)
    protected ObjectRefType hatZEBParameterliste;
    @XmlElement(name = "hat_ZEB_Ereignis")
    protected List<ObjectRefType> hatZEBEreignis;

    /**
     * Gets the value of the okstraid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKSTRAID() {
        return okstraid;
    }

    /**
     * Sets the value of the okstraid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKSTRAID(String value) {
        this.okstraid = value;
    }

    /**
     * Gets the value of the zuBeschriftung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuBeschriftung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuBeschriftung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getZuBeschriftung() {
        if (zuBeschriftung == null) {
            zuBeschriftung = new ArrayList<ObjectRefType>();
        }
        return this.zuBeschriftung;
    }

    /**
     * Gets the value of the referenziertFremddatenbestand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenziertFremddatenbestand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenziertFremddatenbestand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getReferenziertFremddatenbestand() {
        if (referenziertFremddatenbestand == null) {
            referenziertFremddatenbestand = new ArrayList<ObjectRefType>();
        }
        return this.referenziertFremddatenbestand;
    }

    /**
     * Gets the value of the referenziertFremdobjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenziertFremdobjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenziertFremdobjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getReferenziertFremdobjekt() {
        if (referenziertFremdobjekt == null) {
            referenziertFremdobjekt = new ArrayList<ObjectRefType>();
        }
        return this.referenziertFremdobjekt;
    }

    /**
     * Gets the value of the zuKommunikationsobjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuKommunikationsobjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuKommunikationsobjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getZuKommunikationsobjekt() {
        if (zuKommunikationsobjekt == null) {
            zuKommunikationsobjekt = new ArrayList<ObjectRefType>();
        }
        return this.zuKommunikationsobjekt;
    }

    /**
     * Gets the value of the kurzbezeichnungZEBKamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKurzbezeichnungZEBKamp() {
        return kurzbezeichnungZEBKamp;
    }

    /**
     * Sets the value of the kurzbezeichnungZEBKamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKurzbezeichnungZEBKamp(String value) {
        this.kurzbezeichnungZEBKamp = value;
    }

    /**
     * Gets the value of the zebProjekt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZEBProjekt() {
        return zebProjekt;
    }

    /**
     * Sets the value of the zebProjekt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZEBProjekt(String value) {
        this.zebProjekt = value;
    }

    /**
     * Gets the value of the hauptmessverfahren property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHauptmessverfahren() {
        return hauptmessverfahren;
    }

    /**
     * Sets the value of the hauptmessverfahren property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHauptmessverfahren(String value) {
        this.hauptmessverfahren = value;
    }

    /**
     * Gets the value of the zweck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZweck() {
        return zweck;
    }

    /**
     * Sets the value of the zweck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZweck(String value) {
        this.zweck = value;
    }

    /**
     * Gets the value of the umfang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmfang() {
        return umfang;
    }

    /**
     * Sets the value of the umfang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmfang(String value) {
        this.umfang = value;
    }

    /**
     * Gets the value of the zeitabschnitt property.
     * 
     * @return
     *     possible object is
     *     {@link ZeitabschnittPropertyType }
     *     
     */
    public ZeitabschnittPropertyType getZeitabschnitt() {
        return zeitabschnitt;
    }

    /**
     * Sets the value of the zeitabschnitt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeitabschnittPropertyType }
     *     
     */
    public void setZeitabschnitt(ZeitabschnittPropertyType value) {
        this.zeitabschnitt = value;
    }

    /**
     * Gets the value of the hatZEBObjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hatZEBObjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHatZEBObjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getHatZEBObjekt() {
        if (hatZEBObjekt == null) {
            hatZEBObjekt = new ArrayList<ObjectRefType>();
        }
        return this.hatZEBObjekt;
    }

    /**
     * Gets the value of the hatZEBSubjekt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hatZEBSubjekt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHatZEBSubjekt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getHatZEBSubjekt() {
        if (hatZEBSubjekt == null) {
            hatZEBSubjekt = new ArrayList<ObjectRefType>();
        }
        return this.hatZEBSubjekt;
    }

    /**
     * Gets the value of the hatZEBParameterliste property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRefType }
     *     
     */
    public ObjectRefType getHatZEBParameterliste() {
        return hatZEBParameterliste;
    }

    /**
     * Sets the value of the hatZEBParameterliste property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRefType }
     *     
     */
    public void setHatZEBParameterliste(ObjectRefType value) {
        this.hatZEBParameterliste = value;
    }

    /**
     * Gets the value of the hatZEBEreignis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hatZEBEreignis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHatZEBEreignis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectRefType }
     * 
     * 
     */
    public List<ObjectRefType> getHatZEBEreignis() {
        if (hatZEBEreignis == null) {
            hatZEBEreignis = new ArrayList<ObjectRefType>();
        }
        return this.hatZEBEreignis;
    }

}
