//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.09 at 04:49:50 PM EET 
//


package com.eurodyn.okstra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Zustand_BauteilgruppeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zustand_BauteilgruppeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Bauteilgruppe" type="{http://www.okstra.de/okstra/2.018.2/okstra-basis}KeyValuePropertyType"/&gt;
 *         &lt;element name="Zustandsnote" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="Substanzkennzahl" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zustand_BauteilgruppeType", propOrder = {
    "bauteilgruppe",
    "zustandsnote",
    "substanzkennzahl"
})
public class ZustandBauteilgruppeType {

    @XmlElement(name = "Bauteilgruppe", required = true)
    protected KeyValuePropertyType bauteilgruppe;
    @XmlElement(name = "Zustandsnote")
    protected double zustandsnote;
    @XmlElement(name = "Substanzkennzahl")
    protected double substanzkennzahl;

    /**
     * Gets the value of the bauteilgruppe property.
     * 
     * @return
     *     possible object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public KeyValuePropertyType getBauteilgruppe() {
        return bauteilgruppe;
    }

    /**
     * Sets the value of the bauteilgruppe property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyValuePropertyType }
     *     
     */
    public void setBauteilgruppe(KeyValuePropertyType value) {
        this.bauteilgruppe = value;
    }

    /**
     * Gets the value of the zustandsnote property.
     * 
     */
    public double getZustandsnote() {
        return zustandsnote;
    }

    /**
     * Sets the value of the zustandsnote property.
     * 
     */
    public void setZustandsnote(double value) {
        this.zustandsnote = value;
    }

    /**
     * Gets the value of the substanzkennzahl property.
     * 
     */
    public double getSubstanzkennzahl() {
        return substanzkennzahl;
    }

    /**
     * Sets the value of the substanzkennzahl property.
     * 
     */
    public void setSubstanzkennzahl(double value) {
        this.substanzkennzahl = value;
    }

}
